credentials:
  usernames:
    admin:  # questo è l'utente admin predefinito
      email: admin@admin.com
      name: Admin
      password: $2b$12$LQgbY1wKzZ8J5jBzqXnK9uqr6AyvtGNo.XeYF1SYyuXGZNHqyqsUe  # password: admin123
cookie:
  expiry_days: 30
  key: some_signature_key
  name: forex_auth_cookie
preauthorized:
  emails:
    - admin@admin.com
